//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttractionsImg
    {
        public int num { get; set; }
        public string id { get; set; }
        public string Picture { get; set; }
        public string Picdescribe { get; set; }
        public System.DateTime Createdate { get; set; }
        public string CreateName { get; set; }
    
        public virtual Attractions Attractions { get; set; }
    }
}
